[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
src = "src"
script = "script"
out = "out"
libs = ["lib"]

eth_rpc_url = "${RPC_URL}"

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
